<?php
/**
 * DefaultApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Cheevos API
 *
 * API for Hydra's achievements, quests, and user reporting.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiClient;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * DefaultApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class DefaultApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test case for achievementCategoriesAllGet
     *
     * .
     *
     */
    public function testAchievementCategoriesAllGet()
    {

    }

    /**
     * Test case for achievementCategoryIdDelete
     *
     * .
     *
     */
    public function testAchievementCategoryIdDelete()
    {

    }

    /**
     * Test case for achievementCategoryIdGet
     *
     * .
     *
     */
    public function testAchievementCategoryIdGet()
    {

    }

    /**
     * Test case for achievementCategoryIdPut
     *
     * .
     *
     */
    public function testAchievementCategoryIdPut()
    {

    }

    /**
     * Test case for achievementCategoryPut
     *
     * .
     *
     */
    public function testAchievementCategoryPut()
    {

    }

    /**
     * Test case for achievementIdDelete
     *
     * .
     *
     */
    public function testAchievementIdDelete()
    {

    }

    /**
     * Test case for achievementIdGet
     *
     * .
     *
     */
    public function testAchievementIdGet()
    {

    }

    /**
     * Test case for achievementIdPut
     *
     * .
     *
     */
    public function testAchievementIdPut()
    {

    }

    /**
     * Test case for achievementPut
     *
     * .
     *
     */
    public function testAchievementPut()
    {

    }

    /**
     * Test case for achievementsAllGet
     *
     * .
     *
     */
    public function testAchievementsAllGet()
    {

    }

    /**
     * Test case for achievementsProgressGet
     *
     * .
     *
     */
    public function testAchievementsProgressGet()
    {

    }

    /**
     * Test case for achievementsProgressIdDelete
     *
     * .
     *
     */
    public function testAchievementsProgressIdDelete()
    {

    }

    /**
     * Test case for achievementsProgressIdGet
     *
     * .
     *
     */
    public function testAchievementsProgressIdGet()
    {

    }

    /**
     * Test case for achievementsProgressIdPut
     *
     * .
     *
     */
    public function testAchievementsProgressIdPut()
    {

    }

    /**
     * Test case for achievementsProgressPut
     *
     * .
     *
     */
    public function testAchievementsProgressPut()
    {

    }

    /**
     * Test case for incrementPost
     *
     * .
     *
     */
    public function testIncrementPost()
    {

    }

    /**
     * Test case for statsGet
     *
     * .
     *
     */
    public function testStatsGet()
    {

    }

}
