<?php
/**
 * Stat
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swaagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Cheevos API
 *
 * API for Hydra's achievements, quests, and user reporting.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;

/**
 * Stat Class Doc Comment
 *
 * @category    Class */
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class Stat {
    const VISIT = 'visit';
    const ARTICLE_EDIT = 'article_edit';
    const ARTICLE_WATCH = 'article_watch';
    const ARTICLE_CREATE = 'article_create';
    const ARTICLE_DELETE = 'article_delete';
    const ARTICLE_MOVE = 'article_move';
    const ARTICLE_MERGE = 'article_merge';
    const ARTICLE_PROTECT = 'article_protect';
    const ADMIN_BLOCK_IP = 'admin_block_ip';
    const ADMIN_PATROL = 'admin_patrol';
    const CURSE_PROFILE_COMMENT = 'curse_profile_comment';
    const CURSE_PROFILE_ADD_FRIEND = 'curse_profile_add_friend';
    const CURSE_PROFILE_EDIT = 'curse_profile_edit';
    const SEND_EMAIL = 'send_email';
    const FILE_UPLOAD = 'file_upload';
    const WIKI_POINTS = 'wiki_points';
    const CURSE_PROFILE_EDIT_FAV_WIKI = 'curse_profile_edit_fav_wiki';
    const CURSE_PROFILE_COMMENT_REPLY = 'curse_profile_comment_reply';
    const CURSE_PROFILE_EDIT_LINK_XBL = 'curse_profile_edit_link_xbl';
    const CURSE_PROFILE_EDIT_LINK_PSN = 'curse_profile_edit_link_psn';
    const CURSE_PROFILE_EDIT_LINK_STEAM = 'curse_profile_edit_link_steam';
    const CURSE_PROFILE_EDIT_LINK_FACEBOOK = 'curse_profile_edit_link_facebook';
    const CURSE_PROFILE_EDIT_LINK_TWITTER = 'curse_profile_edit_link_twitter';
    const CURSE_PROFILE_EDIT_LINK_REDDIT = 'curse_profile_edit_link_reddit';
    

    
}

