<?php
/**
 * AchievementCriteriaTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Cheevos API
 *
 * API for Hydra's achievements, quests, and user reporting.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * AchievementCriteriaTest Class Doc Comment
 *
 * @category    Class */
// * @description Rules for awarding an achievement
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class AchievementCriteriaTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "AchievementCriteria"
     */
    public function testAchievementCriteria()
    {

    }

    /**
     * Test attribute "stats"
     */
    public function testPropertyStats()
    {

    }

    /**
     * Test attribute "value"
     */
    public function testPropertyValue()
    {

    }

    /**
     * Test attribute "streak"
     */
    public function testPropertyStreak()
    {

    }

    /**
     * Test attribute "streak_progress_required"
     */
    public function testPropertyStreakProgressRequired()
    {

    }

    /**
     * Test attribute "streak_reset_to_zero"
     */
    public function testPropertyStreakResetToZero()
    {

    }

    /**
     * Test attribute "per_site_progress_maximum"
     */
    public function testPropertyPerSiteProgressMaximum()
    {

    }

    /**
     * Test attribute "category_id"
     */
    public function testPropertyCategoryId()
    {

    }

    /**
     * Test attribute "achievement_ids"
     */
    public function testPropertyAchievementIds()
    {

    }

}
