<?php
/**
 * AchievementProgressTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Cheevos API
 *
 * API for Hydra's achievements, quests, and user reporting.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * AchievementProgressTest Class Doc Comment
 *
 * @category    Class */
// * @description Respresents a user&#39;s progress toward an achievement.  Can be manually awarded, which will cause the achievement progress to ignore automatic mechanisms of awarding through stats.
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class AchievementProgressTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "AchievementProgress"
     */
    public function testAchievementProgress()
    {

    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {

    }

    /**
     * Test attribute "achievement_id"
     */
    public function testPropertyAchievementId()
    {

    }

    /**
     * Test attribute "user_id"
     */
    public function testPropertyUserId()
    {

    }

    /**
     * Test attribute "site_id"
     */
    public function testPropertySiteId()
    {

    }

    /**
     * Test attribute "site_key"
     */
    public function testPropertySiteKey()
    {

    }

    /**
     * Test attribute "earned"
     */
    public function testPropertyEarned()
    {

    }

    /**
     * Test attribute "manual_award"
     */
    public function testPropertyManualAward()
    {

    }

    /**
     * Test attribute "awarded_at"
     */
    public function testPropertyAwardedAt()
    {

    }

    /**
     * Test attribute "notified"
     */
    public function testPropertyNotified()
    {

    }

}
