<?php
/**
 * StatProgressTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Cheevos API
 *
 * API for Hydra's achievements, quests, and user reporting.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * StatProgressTest Class Doc Comment
 *
 * @category    Class */
// * @description Represents a statistic for a user on a specific site; or, if site_id is 0, a statistic for a user across all sites.  When streak_type is not none, this stat is used for streak achievements.  Not all stats will have streak progress, and not all streak periods will be available--streak progress is only tracked when a corresponding streak achievement exists.
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class StatProgressTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "StatProgress"
     */
    public function testStatProgress()
    {

    }

    /**
     * Test attribute "stat"
     */
    public function testPropertyStat()
    {

    }

    /**
     * Test attribute "user_id"
     */
    public function testPropertyUserId()
    {

    }

    /**
     * Test attribute "site_id"
     */
    public function testPropertySiteId()
    {

    }

    /**
     * Test attribute "streak_type"
     */
    public function testPropertyStreakType()
    {

    }

    /**
     * Test attribute "count"
     */
    public function testPropertyCount()
    {

    }

    /**
     * Test attribute "last_incremented"
     */
    public function testPropertyLastIncremented()
    {

    }

}
