name: PHPUnit / PHPCS / Phan
on:
  pull_request:
    branches: '**'

  push:
    branches: [ master, MW_1_37, REL1_39 ]

jobs:
  build:
    strategy:
      matrix:
        php_version: ['8.0']
        mw: ['REL1_39']

    runs-on: ubuntu-latest
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php_version }}
          # We don't run any coverage, so we should set this parameter to none
          # as this will disable xdebug which slows all processes significantly
          coverage: none
          extensions: ast

      - name: Checkout Mediawiki
        uses: actions/checkout@v4
        with:
          repository: wikimedia/mediawiki
          ref: ${{ matrix.mw }}

      - uses: actions/checkout@v4
        with:
          path: extensions/Cheevos

      - name: Checkout Twiggy (dependency) extension
        uses: actions/checkout@v4
        with:
          repository: Wikia/mediawiki-extensions-Twiggy
          path: extensions/Twiggy

      - name: Checkout MobileFrontend (dependency) extension
        uses: actions/checkout@v4
        with:
          repository: wikimedia/mediawiki-extensions-MobileFrontend
          path: extensions/MobileFrontend
          ref: ${{ matrix.mw }}

      - name: Checkout HydraCore (dependency) extension
        uses: actions/checkout@v4
        with:
          repository: Wikia/mediawiki-extensions-HydraCore
          path: extensions/HydraCore

      - name: Checkout Cheevos extension
        uses: actions/checkout@v4
        with:
          path: extensions/Cheevos

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-v3-${{ hashFiles('**/composer.lock') }}

      - name: Install composer dependencies
        if: steps.composer-cache.outputs.cache-hit != 'true'
        working-directory: ./extensions/Cheevos
        run: composer install --prefer-dist --no-progress

      - name: Run PHPCS
        working-directory: ./extensions/Cheevos
        run: composer phpcs

      - name: Run Phan static analysis
        working-directory: ./extensions/Cheevos
        run: composer phan
        # Allow Phan to fail due to a high number of carryovers from the MW 1.39 upgrade
        continue-on-error: true

      - name: Run jsonlint
        working-directory: ./extensions/Cheevos
        run: composer jsonlint

      - name: Start MySQL
        run: sudo systemctl start mysql.service

      - name: Install MediaWiki composer dependencies
        run: composer update --prefer-dist --no-progress

      - name: Install & configure MediaWiki
        run: |
          php maintenance/install.php --dbtype mysql --dbuser root --dbpass root --pass TestPassword testwiki TestAdmin

          echo 'error_reporting( E_ALL | E_STRICT );' >> LocalSettings.php
          echo 'ini_set( "display_errors", 1 );' >> LocalSettings.php
          echo '$wgShowExceptionDetails = true;' >> LocalSettings.php
          echo '$wgShowDBErrorBacktrace = true;' >> LocalSettings.php
          echo '$wgDevelopmentWarnings = true;' >> LocalSettings.php

          echo '$wgNamespacesForEditPoints = [ NS_MAIN ];' >> LocalSettings.php

          echo 'wfLoadExtension( "'Twiggy'" );' >> LocalSettings.php
          echo 'wfLoadExtension( "'HydraCore'" );' >> LocalSettings.php
          echo 'wfLoadExtension( "'MobileFrontend'" );' >> LocalSettings.php
          echo 'wfLoadExtension( "'Cheevos'" );' >> LocalSettings.php

      - name: Run schema changes
        run: php maintenance/update.php --quick

      - name: Run PHPUnit tests
        run: php tests/phpunit/phpunit.php extensions/Cheevos/tests
